---
permalink: intro-family.html 
keywords: introduction, what is ONTAP systems, AFF, AFX, FAS, ASA, all-flash, ONTAP 
summary: NetApp 的 ONTAP 系列儲存系統是專為企業應用程式所設計、這些應用程式需要易於管理、快速且安全的儲存設備、並具備企業級的可靠性和持續的資料存取。 
---
= 瞭解 ONTAP 硬體系統
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp 的 ONTAP 硬體系統是專為企業應用程式所設計、這些應用程式需要易於管理、快速且安全的儲存設備、並具備企業級的可靠性和持續的資料存取。

NetApp 的ONTAP硬體系統提供全快閃、混合快閃記憶體和僅 HDD 配置，讓您可以選擇最符合您的效能、容量和成本要求的儲存媒體組合。

您可以叢集不同的模型組合、在同一個儲存系統上執行混合式工作負載、並使用最新技術新增新一代的儲存設備、以建構您的環境。



== All Flash FAS 更新（Solid-Flash）AFF 系統

NVMe AFF 型的不間斷資料系統是專為虛擬化環境打造的強大橫向擴充平台、可部署為獨立系統、或是NetApp ONTAP 的不間斷資料組態中的高效能層。

All Flash FAS 支援多種工作負載、尤其是需要高效能、低延遲和可靠性的VDI和資料庫、是業務關鍵應用程式的理想選擇。

* https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["閱讀 AFF A 系列資料表"^]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["閱讀 AFF C 系列資料表"^]




== AFX

NetApp AFX 是一款企業級分解式全快閃儲存系統，可提供平行檔案系統和利基 AI 儲存解決方案的所有效能優勢，但在簡單、安全且完全整合的企業級平台上。

* https://www.netapp.com/pdf.html?item=/media/142853-ds-3466-netapp-afx-datasheet.pdf["閱讀 AFX 數據表"^]
* https://docs.netapp.com/us-en/ontap-afx/get-started/ontap-afx-storage.html["了解有關 AFX 存儲的更多信息"^]




== All Flash SAN Array （ ASA ）系統

NetApp All Flash SAN Array （ ASA ）提供簡化且專屬的 SAN 體驗、可透過 FCP 或 iSCSI 傳輸協定、為企業關鍵任務資料庫及其他 SAN 工作負載提供持續的資料可用度。

.ASA r2 系統
全新NetApp ASA r2 系統（ASA A1K、 ASA A70、 ASA A90、 ASA A20、 ASA A30、 ASA A50 和 C30）提供統一的硬體和軟體解決方案，可針對僅使用 SAN 的客戶的需求打造簡化的體驗。

在 ASA R2 系統上、 ONTAP 軟體和系統管理員經過簡化、可支援基本的 SAN 功能、同時移除 SAN 環境中不支援的功能和功能可見度。

* https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["閱讀 ASA 資料表"^]
* 深入瞭解link:https://docs.netapp.com/us-en/asa-r2/learn-more/hardware-comparison.html["相較於 ASA 系統、全新的 ASA R2 系統"^]
* 請參閱中 ASA 和 ASA R2 系統的完整組態支援和限制 https://hwu.netapp.com/["NetApp Hardware Universe"^]




== 支援混合式Flash系統FAS

混合式Flash系統是專為共享、整合式SAN和NAS環境所打造的硬體平台、需要豐富的資料管理功能和輕鬆的雲端連線。FAS

藉由高可用度的硬體FAS 、將Flash與傳統旋轉式磁碟機的理想組合結合、使混合式Flash系統以符合成本效益的方式滿足工作負載需求。它是備份與保留、整合一般商業應用程式及分散式內容的理想選擇。

https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["閱讀 FAS 資料表"^]



== MetroCluster

ONTAP 的硬體儲存系統設定有 ONTAP 的 MetroCluster 功能、提供結合陣列式叢集與同步複寫的解決方案、可提供持續可用度、零資料遺失。此功能組態會立即複製每筆交易的所有關鍵任務資料、讓您不中斷地存取應用程式和資料。MetroCluster

不像標準資料複寫解決方案、MetroCluster 它能與主機環境無縫搭配運作、提供持續的資料可用度、同時免除建立及維護複雜容錯移轉指令碼的需求。

https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["深入瞭解 MetroCluster"^]



== 軟件ONTAP

ONTAP 資料管理軟體是叢集式儲存軟體、可驅動 ONTAP 硬體系統。ONTAP 軟體採用全域命名空間、最多可支援 24 個所有類型的硬體節點、支援統一化儲存（區塊和檔案）、可讓您使用 ONTAP 系統管理員 GUI 來管理大量的工作負載整合。

https://www.netapp.com/pdf.html?item=/media/7413-ds-3231.pdf["閱讀 ONTAP 軟體資料表"^]

.以取得更多資訊
* https://docs.netapp.com/us-en/ontap-systems/index.html["ONTAP 硬體系統文件"^]
* https://docs.netapp.com/us-en/ontap-metrocluster/index.html["文件MetroCluster"^]
* https://docs.netapp.com/us-en/ontap/index.html["文件ONTAP"^]

