---
settings:
  name: AFF and FAS Family
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,zh-cn,ko-kr
sidebar:
  entries:
  - title: 不再需要使用本技術AFF FAS
    url: "/index.html"
product-family:
  search: clouddocs-ontap-systems_main-prod,clouddocs-ontap-systems-upgrade_main-prod,clouddocs-ontap-systems-switches_main-prod,clouddocs-ontap-metrocluster_main-prod
  sidebarlinks:
  - title: 全部
    tags: tag_storage_management,tag_storage_upgrade,tag_storage_hardware,tag_get_started
    class: active
  - title: 開始使用
    tags: tag_get_started
  - title: 系統硬體
    tags: tag_storage_hardware
  - title: 系統升級
    tags: tag_storage_upgrade
  tiles:
  - title: 深入瞭AFF 解功能與FAS 功能
    icon: "./media/family.png"
    url: intro-family.html
    summary: 瞭解AFF 關於儲存FAS 系統的功能性與功能性系列。
    tags: all, tag_get_started
  - title: 安裝與維護AFF FAS
    icon: "./media/icon-onprem.png"
    url: https://docs.netapp.com/us-en/ontap-systems/index.html
    summary: 安裝並維護AFF 您的不穩定、FAS 不穩定或所有SAN Array系統。
    tags: all, tag_storage_hardware
  - title: 升級版AFF FAS
    icon: "./media/upgrade.png"
    url: https://docs.netapp.com/us-en/ontap-systems-upgrade/index.html
    summary: 升級AFF 您的功能性和FAS 功能性儲存系統。
    tags: all, tag_storage_upgrade
  - title: 叢集與儲存交換器
    icon: "./media/switch.png"
    url: https://docs.netapp.com/us-en/ontap-systems-switches/index.html
    summary: 安裝、升級及維護您的叢集與儲存交換器。
    tags: all, tag_storage_hardware, tag_storage_upgrade
  - title: ONTAP MetroCluster
    icon: "./media/metrocluster.png"
    url: https://docs.netapp.com/us-en/ontap-metrocluster/index.html
    summary: 安裝及升級MetroCluster 或擴充您的支援功能、並執行災難恢復。
    tags: all, tag_storage_upgrade
  - title: 本文檔 ONTAP
    icon: "./media/family.png"
    url: https://docs.netapp.com/us-en/ontap-family/index.html
    summary: 請使用ONTAP 《產品介紹》文件、瞭解如何設定ONTAP 功能、為用戶端配置儲存設備、以及如何使用System Manager或CLI來保護及管理資料。
    tags: all, tag_storage_management
