---
settings:
  name: ONTAP hardware systems
  search: ontap-systems,ontap-systems-upgrade,ontap-systems-switches,ontap-metrocluster
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: ONTAP 硬體系統文件
    url: "/index.html"
